version: "3.8"
services:

  nginx:
    image: nginx:alpine
    networks:
      - router
    deploy:
      replicas: 5 
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        ingress.host: my-service.company.tld

networks:
  router:
    external: true
    name: router