version: "3.8"
services:

  nginx:
    image: nginx:alpine
    networks:
      - routing
    deploy:
      replicas: 5 
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      labels:
        router.host: my-service.company.tld

networks:
  routing:
    external: true
    name: routing